source 'https://rubygems.org'

gem 'dashing'

## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.9.0'

gem 'simple-rss'

gem 'koala'
gem 'google-api-client'

gem 'net/http'
gem 'json'
